name = "motolap-frontend"
main = "src/worker.js"
compatibility_date = "2024-09-23"
account_id = "74762af8c4ebccbb091ce61c93b9185a"

# Cloudflare Workers Assets configuration
# "binding" allows us to access the assets in the worker (env.ASSETS)
[assets]
directory = "./dist"
binding = "ASSETS"
