DEFAULT_TH_ON = 0.6
DEFAULT_TH_OFF = 0.3
DEFAULT_MIN_SPEED_KPH = 10.0

DEFAULT_GAP_LIMIT_S = 0.3
DEFAULT_MIN_DURATION_S = 0.4

DEFAULT_TRACKMAP_RADIUS_M = 60.0

# Formula Table thresholds
BRK_ON_THRESHOLD_G = -0.15
CRN_ON_THRESHOLD_G = 0.2
TPS_ON_THRESHOLD_G = 0.05
GRAVITY_MPS2 = 9.80665

BRAKE_JERK_INITIAL_WINDOW_S = 0.5

